(function(){
  var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  function nativeReveals(){var targets=document.querySelectorAll('.reveal,.split-reveal');if(!('IntersectionObserver'in window)){targets.forEach(function(el){el.classList.add('visible')});return}var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}})},{threshold:.14});targets.forEach(function(el){observer.observe(el)})}
  function createVideoScrubber(video){var target=0,lastCommitted=-1,raf=0,seeking=false,frameStep=1/30;function request(){if(!raf)raf=requestAnimationFrame(commit)}function commit(){raf=0;if(!isFinite(video.duration)||video.readyState<2||seeking)return;var next=Math.max(0,Math.min(video.duration,target));if(Math.abs(next-lastCommitted)<frameStep&&next!==0&&next!==video.duration)return;lastCommitted=next;seeking=true;try{video.currentTime=next}catch(e){seeking=false}}function resume(){seeking=false;if(Math.abs(target-lastCommitted)>=frameStep*.5)request()}video.addEventListener('seeked',resume);video.addEventListener('error',function(){seeking=false});return{setProgress:function(progress){target=Math.max(0,Math.min(1,progress))*video.duration;request()}}}
  function setupVideoFallback(video,hero,scrubber){var wrapper=hero.parentElement,raf=0;function sync(){raf=0;var rect=wrapper.getBoundingClientRect(),range=Math.max(1,wrapper.offsetHeight-innerHeight),progress=Math.max(0,Math.min(1,-rect.top/range));scrubber.setProgress(progress);hero.querySelector('.hero-copy').style.transform='translateY('+(-progress*14)+'px)'}function request(){if(!raf)raf=requestAnimationFrame(sync)}window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',request);request()}
  function setupHeroFilm(hero){var video=hero.querySelector('.hero-video');if(!video)return;var portrait=window.matchMedia&&window.matchMedia('(max-width: 760px) and (orientation: portrait)'),started=false,scrubber;function ready(){if(video.dataset.scrollReady)return;video.dataset.scrollReady='true';video.pause();video.classList.add('is-ready');try{video.currentTime=.001}catch(e){}if(reduced)return;scrubber=createVideoScrubber(video);setupVideoFallback(video,hero,scrubber)}function stopVideo(){video.pause();video.removeAttribute('src');video.load();video.classList.remove('is-ready');video.removeAttribute('data-scroll-ready');started=false;scrubber=null}function startVideo(){if(started)return;started=true;video.addEventListener('loadedmetadata',ready,{once:true});video.addEventListener('error',function(){video.classList.remove('is-ready')},{once:true});video.src=video.dataset.src;video.load();if(video.readyState>=1)ready()}function syncHeroMedia(){var usePortrait=portrait&&portrait.matches;hero.classList.toggle('uses-portrait-image',usePortrait);if(usePortrait){stopVideo();hero.querySelector('.hero-copy').style.transform='';return}startVideo()}if(portrait){if(portrait.addEventListener)portrait.addEventListener('change',syncHeroMedia);else portrait.addListener(syncHeroMedia)}syncHeroMedia();}
  window.APMAnimations={init:function(){nativeReveals();var hero=document.querySelector('.hero');setTimeout(function(){hero.classList.add('ready')},150);setupHeroFilm(hero);if(!window.gsap||!window.ScrollTrigger||reduced)return;gsap.registerPlugin(ScrollTrigger);
    gsap.to('.hero-light',{xPercent:-5,yPercent:8,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});gsap.to('.hero-shade',{opacity:.86,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:true}});
    gsap.from('.story-portrait',{y:90,rotate:2,scrollTrigger:{trigger:'.intro',start:'top 75%',end:'bottom 45%',scrub:true}});gsap.from('.heritage-media',{clipPath:'inset(8% 0 8% 0)',scrollTrigger:{trigger:'.heritage',start:'top 82%',end:'top 20%',scrub:true}});
    gsap.utils.toArray('.process-card').forEach(function(card,i){gsap.from(card,{y:70,opacity:0,duration:.9,delay:i*.08,scrollTrigger:{trigger:'.process-stage',start:'top 78%'}});gsap.to(card.querySelector('.process-photo'),{yPercent:i===1?-7:7,ease:'none',scrollTrigger:{trigger:card,start:'top bottom',end:'bottom top',scrub:true}})});gsap.from('.showroom-image',{clipPath:'inset(0 0 100% 0)',scrollTrigger:{trigger:'.showroom',start:'top 70%',end:'top 35%',scrub:true}});gsap.utils.toArray('.editorial-image,.showroom-image').forEach(function(el){gsap.fromTo(el,{scale:1.08},{scale:1,ease:'none',scrollTrigger:{trigger:el.parentElement,start:'top bottom',end:'bottom top',scrub:true}})})
  }};
})();
