/* Interaction layer: data-driven galleries, product viewer and resilient media loading. */
(function(){
  var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))},config=window.SITE_CONFIG;
  function endLoader(){$('.loader').classList.add('done')}document.addEventListener('DOMContentLoaded',function(){setTimeout(endLoader,1600)});window.addEventListener('load',function(){setTimeout(endLoader,250)});setTimeout(endLoader,2100);
  function loadImage(el,src,fallback){if(!src)return;var image=new Image();image.onload=function(){el.style.backgroundImage='url("'+src+'")';el.classList.add('loaded')};image.onerror=function(){if(fallback&&!el.dataset.retried){el.dataset.retried='true';loadImage(el,fallback);return}el.classList.add('image-fallback')};image.src=src}
  $$('.image-load').forEach(function(el){loadImage(el,el.dataset.src)});
  function mapConfig(){var mapUrl=config.maps,wa='https://wa.me/'+config.whatsapp+'?text='+encodeURIComponent('Hi APM TEX, I would like to know more about your collections.');$$('.config-map').forEach(function(a){a.href=mapUrl;a.target='_blank';a.rel='noreferrer'});$$('.config-phone').forEach(function(a){a.href='tel:'+config.phone;a.textContent=config.phone});$$('.config-whatsapp').forEach(function(a){a.href=wa;a.target='_blank';a.rel='noreferrer'});var frame=$('.map-frame');if(frame)frame.src='https://www.google.com/maps?q='+encodeURIComponent('7H95+W68, Mahendragiri R.F., Vadakankulam, Tamil Nadu 629301')+'&output=embed'}mapConfig();
  var list=$('#collection-list'),showroom=$('.showroom-modal'),viewer=$('.product-viewer'),currentProducts=[],currentIndex=0,currentCategory='',currentShowroom='';
  function openCollection(key){var data=window.SHOWROOMS[key];if(!data)return;currentShowroom=key;$('#showroom-title').textContent=data.label;$('#showroom-tagline').textContent=data.tagline;var filters=$('.showroom-filters');filters.innerHTML=Object.keys(data.categories).map(function(cat,i){return '<button class="gallery-filter '+(!i?'active':'')+'" data-category="'+cat+'">'+cat+'</button>'}).join('');filters.querySelectorAll('button').forEach(function(button){button.addEventListener('click',function(){renderGallery(button.dataset.category);filters.querySelectorAll('button').forEach(function(b){b.classList.toggle('active',b===button)})})});renderGallery(Object.keys(data.categories)[0]);showroom.showModal();showroom.scrollTop=0;$('.modal-close').focus()}
  function renderGallery(category){currentCategory=category;currentProducts=window.SHOWROOMS[currentShowroom].categories[category];var gallery=$('.product-gallery');gallery.innerHTML=currentProducts.map(function(product,index){var backup=currentProducts[(index+1)%currentProducts.length].image;return '<button class="product-tile" data-product="'+index+'" aria-label="View '+product.name+'"><span class="product-image" data-src="'+product.image+'" data-fallback="'+backup+'"></span><span class="product-meta">'+product.name+' <i>View ↗</i></span></button>'}).join('');gallery.querySelectorAll('.product-image').forEach(function(el){loadImage(el,el.dataset.src,el.dataset.fallback)});gallery.querySelectorAll('.product-tile').forEach(function(tile){tile.addEventListener('click',function(){openProduct(+tile.dataset.product)})});document.dispatchEvent(new Event('showroom:gallery-rendered'))}
  function openProduct(index){currentIndex=index;showProduct();viewer.showModal();$('.viewer-close').focus()}
  function showProduct(){var product=currentProducts[currentIndex],image=$('.viewer-image'),backup=currentProducts[(currentIndex+1)%currentProducts.length];image.style.backgroundImage='';delete image.dataset.retried;loadImage(image,product.image,backup&&backup.image);$('#viewer-category').textContent=window.SHOWROOMS[currentShowroom].label+' / '+currentCategory;$('#viewer-title').textContent=product.name;var message='Hi APM TEX, I am interested in '+window.SHOWROOMS[currentShowroom].label+' → '+currentCategory+' ('+product.name+'). How can I buy this?';var wa=$('.viewer-whatsapp');wa.href='https://wa.me/'+config.whatsapp+'?text='+encodeURIComponent(message);wa.target='_blank';wa.rel='noreferrer';var preload=currentProducts[(currentIndex+1)%currentProducts.length];if(preload){var next=new Image();next.src=preload.image}}
  function nextProduct(){currentIndex=(currentIndex+1)%currentProducts.length;showProduct()}function previousProduct(){currentIndex=(currentIndex-1+currentProducts.length)%currentProducts.length;showProduct()}
  if(list){list.innerHTML=window.APMCollections.map(function(c){return '<article class="collection" role="button" tabindex="0" data-key="'+c.key+'"><span class="collection-no">'+c.no+'</span><h3>'+c.title+'</h3><span class="collection-sub">'+c.sub+'</span><span class="collection-arrow">↗</span><span class="collection-preview" data-src="'+c.image+'"></span></article>'}).join('');$$('.collection-preview').forEach(function(el){loadImage(el,el.dataset.src)});$$('.collection').forEach(function(el){function activate(){openCollection(el.dataset.key)}el.addEventListener('click',activate);el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})})}
  $('.modal-close').addEventListener('click',function(){showroom.close()});$('.viewer-close').addEventListener('click',function(){viewer.close()});$('.viewer-next').addEventListener('click',nextProduct);$('.viewer-prev').addEventListener('click',previousProduct);[showroom,viewer].forEach(function(dialog){dialog.addEventListener('click',function(e){if(e.target===dialog)dialog.close()})});window.addEventListener('keydown',function(e){if(viewer.open&&e.key==='ArrowRight')nextProduct();if(viewer.open&&e.key==='ArrowLeft')previousProduct()});
  var startX=0;$('.viewer-image').addEventListener('touchstart',function(e){startX=e.changedTouches[0].screenX},{passive:true});$('.viewer-image').addEventListener('touchend',function(e){var diff=e.changedTouches[0].screenX-startX;if(Math.abs(diff)>45)diff<0?nextProduct():previousProduct()},{passive:true});
  var nav=$('.nav'),toggle=$('.menu-toggle'),panel=$('.menu-panel');window.addEventListener('scroll',function(){nav.classList.toggle('scrolled',scrollY>50)},{passive:true});toggle.addEventListener('click',function(){var open=toggle.classList.toggle('active');toggle.setAttribute('aria-expanded',open);toggle.querySelector('span').textContent=open?'Close':'Menu';panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',!open);document.body.style.overflow=open?'hidden':''});$$('.menu-links a').forEach(function(a){a.addEventListener('click',function(){if(toggle.classList.contains('active'))toggle.click()})});
  if(matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
    /* Keep the cursor at document root: it must never inherit a section's clipping or transform. */
    var cursor=$('.cursor'),label=cursor.querySelector('span'),cursorFrame=0,cursorX=0,cursorY=0;
    document.body.appendChild(cursor);
    /* Native modal dialogs enter the browser's top layer, above body children.
       Portal the same cursor into the active dialog only while it is open. */
    function placeCursorInActiveLayer(){var dialogs=$$('dialog[open]'),host=dialogs.length?dialogs[dialogs.length-1]:document.body;if(cursor.parentElement!==host)host.appendChild(cursor)}
    new MutationObserver(placeCursorInActiveLayer).observe(document.body,{subtree:true,attributes:true,attributeFilter:['open'],childList:true});
    placeCursorInActiveLayer();
    function paintCursor(){cursor.style.transform='translate3d('+cursorX+'px,'+cursorY+'px,0) translate(-50%,-50%)';cursor.style.opacity='1';cursor.style.visibility='visible';cursorFrame=0}
    document.addEventListener('pointermove',function(e){cursorX=e.clientX;cursorY=e.clientY;if(!cursorFrame)cursorFrame=requestAnimationFrame(paintCursor)},{passive:true});
    function bindCursorTargets(){return $$('.collection,.editorial-image,.showroom-image,.process-card,.product-tile,.circle-link,.text-link').forEach(function(el){if(el.dataset.cursorBound)return;el.dataset.cursorBound='true';el.addEventListener('mouseenter',function(){cursor.classList.add('is-view');label.textContent='View'});el.addEventListener('mouseleave',function(){cursor.classList.remove('is-view')})})}
    bindCursorTargets();document.addEventListener('showroom:gallery-rendered',bindCursorTargets);
  }
  if(window.APMAnimations)window.APMAnimations.init();
})();
